[workspace]
members = [
    "src-tauri"
]

[dependencies]
tauri = "2.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
sysinfo = "0.23"
memmap2 = "0.6"
