name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'KernelForge ${{ github.ref_name }}'
          releaseBody: |
            ## KernelForge Release ${{ github.ref_name }}
            
            Linux kernel optimizer for gaming performance.
            
            ### Installation
            
            **Debian/Ubuntu:**
            ```bash
            sudo dpkg -i kernelforge_*_amd64.deb
            sudo apt-get install -f  # Install any missing dependencies
            ```
            
            **Fedora/RHEL:**
            ```bash
            sudo rpm -i kernelforge-*.x86_64.rpm
            ```
            
            ### Runtime Dependencies
            
            **Debian/Ubuntu:**
            - libwebkit2gtk-4.1-0
            - libgtk-3-0
            
            **Fedora/RHEL:**
            - webkit2gtk4.1
            - gtk3
            
            See [docs/packaging.md](docs/packaging.md) for detailed installation instructions.
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }}
